name: Java ci/cd with Gradle

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/gsample01
  CONTAINER: gs01

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: setup jdk 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: init with gradle
        uses: gradle/gradle-build-action@v2     

      - run: gradle init  

      - name: build with gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
          arguments: build

      - name: docker image build
        run: docker build -t ${{ env.IMAGE }} .

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker hub push
        run: docker push ${{ env.IMAGE }}

  deploy:
    needs: build
    name: deploy
    runs-on: [self-hosted, label-1]
    steps:
      - name: login dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker run
        run: |
          docker stop ${{ env.CONTAINER }} && docker rm ${{ env.CONTAINER }} && docker rmi ${{ env.IMAGE }}:latest
          docker run -d --name ${{ env.CONTAINER }} -p 50005:50005  ${{ env.IMAGE }}:latest
        
    
